/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-06-24 02:04:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class f_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Study_Spring/Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/anafor/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648006669317L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>고객센터</title>\n");
      out.write("<style>\n");
      out.write("#wrap{\n");
      out.write("	width:100%; \n");
      out.write("	height:auto; \n");
      out.write("	position:relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#top_img{\n");
      out.write("	width: 100%; \n");
      out.write("	height:372px; \n");
      out.write("	background: url(\"imgs/faq.png\") center no-repeat; \n");
      out.write("	position:relative; \n");
      out.write("	margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#top_img .text_box{\n");
      out.write("	position:absolute; \n");
      out.write("	left:150px; \n");
      out.write("	top:100px; \n");
      out.write("}\n");
      out.write("\n");
      out.write("#top_img .text_box p{\n");
      out.write("	line-height: 80px; \n");
      out.write("	font-size:70px; \n");
      out.write("	color:#929292; \n");
      out.write("	text-align:left\n");
      out.write("}\n");
      out.write("\n");
      out.write("#list-top{\n");
      out.write("	width: 1000px;\n");
      out.write("	display: block;\n");
      out.write("	margin: 0 auto;\n");
      out.write("	padding-left:5px;\n");
      out.write("	padding-right:220px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#list-content{\n");
      out.write("	margin-right: 300px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a.btn-empty {\n");
      out.write("	width:70px;\n");
      out.write("	background: #fff; \n");
      out.write("	color: #929292; \n");
      out.write("	text-align:center; \n");
      out.write("	padding:3px 10px; \n");
      out.write("	margin-left:5px;\n");
      out.write("	border: 1px solid #b0b0b0; \n");
      out.write("}\n");
      out.write("\n");
      out.write("input {\n");
      out.write("	height: 30px;\n");
      out.write("	margin-left:5px;\n");
      out.write("	font-size: 15px;\n");
      out.write("	border: 1px solid #b0b0b0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("select {\n");
      out.write("	height: 30px; \n");
      out.write("	border: 1px solid #b0b0b0; \n");
      out.write("	padding : 0 5px; \n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu_form {\n");
      out.write("	width:218px;\n");
      out.write("	height: 100px; \n");
      out.write("	margin: auto; \n");
      out.write("	padding-top: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#wrap #menu {\n");
      out.write("	margin:0 auto; \n");
      out.write("	height: 50px; \n");
      out.write("	cursor: pointer; \n");
      out.write("} \n");
      out.write("\n");
      out.write("#menu ul{ oveflow:hidden;}\n");
      out.write("	\n");
      out.write("#menu ul li{float:left;}\n");
      out.write("\n");
      out.write("#menu ul li a{\n");
      out.write("	font-size:30px;\n");
      out.write("	display: block;\n");
      out.write("	padding: 10px 20px;\n");
      out.write("	border : 1px solid #929292;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu ul li a:hover{\n");
      out.write("	background-color: #b0b0b0;\n");
      out.write("	color: white;	\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu ul li:nth-child(1) a {\n");
      out.write("	border-right: 0px;\n");
      out.write("	background-color : #929292;\n");
      out.write("	color: white;	\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* FAQ */\n");
      out.write("\n");
      out.write("\n");
      out.write(".faq{\n");
      out.write("	background:center;\n");
      out.write("	border-bottom:0px solid #ddd;\n");
      out.write("	width: 1000px;\n");
      out.write("	height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".faq .q{\n");
      out.write("	padding : 15px 30px 15px;\n");
      out.write(" 	background-color: rgba( 105, 106, 173, 0.3 );\n");
      out.write("	color:black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".faq .a{\n");
      out.write("	background:#f1f0f2;\n");
      out.write("	padding: 10px 75px 10px 75px;\n");
      out.write("    line-height: 22px;\n");
      out.write("    padding : 20px 50px;\n");
      out.write("}\n");
      out.write(".a{\n");
      out.write("   font-size: 16px;\n");
      out.write("   text-align : left;\n");
      out.write("}\n");
      out.write(".q{\n");
      out.write("   max-width : 100%;\n");
      out.write("   text-align : left;\n");
      out.write("   font-weight : bold;\n");
      out.write("   font-size: 16px;\n");
      out.write("   border-bottom: 1px solid #bdbdbd;\n");
      out.write("   margin-top: 10px;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("summary { \n");
      out.write("	cursor: pointer; \n");
      out.write("}\n");
      out.write("summary { \n");
      out.write("	list-style: none; \n");
      out.write("}   \n");
      out.write("summary::-webkit-details-marker {\n");
      out.write("   display: none;\n");
      out.write("}   \n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form id=\"wrap\" action=\"f_list.cu\" method=\"post\">\n");
      out.write("	<input type=\"hidden\" name=\"curPage\" value=\"1\" />\n");
      out.write("	<div id=\"top_img\">\n");
      out.write("		<div class=\"text_box\">\n");
      out.write("			<p><b>아나포에서 여러분의<br>소리를 듣습니다</b></p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div id=\"menu_form\">\n");
      out.write("		<div id=\"menu\">\n");
      out.write("			<ul>	\n");
      out.write("				<li><a href=\"f_list.cu\">FAQ</a></li>\n");
      out.write("				<li><a href=\"list.cu\">Q&A</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</form>	\n");
      out.write("<div style=\"margin: auto; width: 1000px;\">\n");
      out.write("	<div class='faq'>\n");
      out.write("	   <div class='faqbody'>\n");
      out.write("	      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	   	</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("	<div>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/page.jsp", out, false);
      out.write("\n");
      out.write("		<!-- jsp 표준 include를 사용하여 설정 -->\n");
      out.write("	</div>	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/customer/f_list.jsp(195,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/f_list.jsp(195,7) '${page.list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${page.list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/customer/f_list.jsp(195,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("vo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("		         <details>\n");
            out.write("		         	");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("		            <summary class='q'>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("			            <img src='imgs/drop-down.png' />\n");
            out.write("		            </summary>\n");
            out.write("		            <pre class='a'>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</pre>\n");
            out.write("		         </details>\n");
            out.write("   	      	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/customer/f_list.jsp(197,12) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/views/customer/f_list.jsp(197,12) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.indent }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/customer/f_list.jsp(197,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("						");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i eq vo.indent ? \"<img src='imgs/re.gif' />\" : \"&nbsp;&nbsp;\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
