/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-06-13 01:33:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/Study_Spring/Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/anafor/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648006669317L));
    _jspx_dependants.put("jar:file:/D:/Study_Spring/Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/anafor/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>상품 주문</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".wrap {\n");
      out.write("	width: 1638px;\n");
      out.write("	height: 759px;\n");
      out.write("	left: 0px;\n");
      out.write("	top: 60px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".img {\n");
      out.write("	width: 796px;\n");
      out.write("	height: 569px;\n");
      out.write("	left: 50px;\n");
      out.write("	top: 106px;\n");
      out.write("	position: absolute;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".text_div {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 600px;\n");
      out.write("	height: 50px;\n");
      out.write("	left: 932px;\n");
      out.write("	top: 130px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#name {\n");
      out.write("	font-weight: bold;\n");
      out.write("	font-size: 22px;\n");
      out.write("	line-height: 50px;\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#name::after {\n");
      out.write("	content: '';\n");
      out.write("	display: block;\n");
      out.write("	height: 2px;\n");
      out.write("	width: 698;\n");
      out.write("	background: #888888;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#price {\n");
      out.write("	color: red;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".a {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 80px;\n");
      out.write("	height: 250px;\n");
      out.write("	line-height: 50px;\n");
      out.write("	left: 947px;\n");
      out.write("	top: 205px;\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".a p {\n");
      out.write("	font-size: 18px;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 230px;\n");
      out.write("	height: 250px;\n");
      out.write("	left: 1090px;\n");
      out.write("	top: 205px;\n");
      out.write("	line-height: 50px;\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b p {\n");
      out.write("	font-size: 16px;\n");
      out.write("	color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".c {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 598px;\n");
      out.write("	height: 99px;\n");
      out.write("	left: 932px;\n");
      out.write("	top: 470px;\n");
      out.write("	border: 1px solid #CCCCCC;\n");
      out.write("	box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n");
      out.write("	border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cnt {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 50px;\n");
      out.write("	height: 25px;\n");
      out.write("	left: 1445px;\n");
      out.write("	top: 485px;\n");
      out.write("	font-size: 16px;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".c #line {\n");
      out.write("	line-height: 50px;\n");
      out.write("	text-align: left;\n");
      out.write("	font-size: 16px;\n");
      out.write("	margin-left: 15px;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".c #line::after {\n");
      out.write("	content: '';\n");
      out.write("	display: block;\n");
      out.write("	height: 1px;\n");
      out.write("	width: 570px;\n");
      out.write("	background: #888888;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".order {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 200px;\n");
      out.write("	height: 80px;\n");
      out.write("	left: 1008px;\n");
      out.write("	top: 595px;\n");
      out.write("	background: #696aad;\n");
      out.write("	border-radius: 20px;\n");
      out.write("	color: white;\n");
      out.write("	border: none;\n");
      out.write("	font-size: 17px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".buy_insert {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 200px;\n");
      out.write("	height: 80px;\n");
      out.write("	left: 1250px;\n");
      out.write("	top: 595px;\n");
      out.write("	background: #808080;\n");
      out.write("	border: none;\n");
      out.write("	border-radius: 20px;\n");
      out.write("	color: white;\n");
      out.write("	font-size: 17px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".total {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 180px;\n");
      out.write("	height: 18px;\n");
      out.write("	left: 1339px;\n");
      out.write("	top: 542px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".total_price {\n");
      out.write("	font-weight: bold;\n");
      out.write("	font-size: 16px;\n");
      out.write("	line-height: 20px;\n");
      out.write("	margin-right: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".money {\n");
      out.write("	position: absolute;\n");
      out.write("	width: 200px;\n");
      out.write("	height: 18px;\n");
      out.write("	left: 1330px;\n");
      out.write("	top: 542px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".money_result {\n");
      out.write("	font-weight: bold;\n");
      out.write("	font-size: 17px;\n");
      out.write("	line-height: 20px;\n");
      out.write("	margin-left: 110px;\n");
      out.write("	color: red;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Chrome, Safari, Edge, Opera */\n");
      out.write("input::-webkit-outer-spin-button, input::-webkit-inner-spin-button {\n");
      out.write("	-webkit-appearance: none;\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Firefox */\n");
      out.write("input[type=number] {\n");
      out.write("	-moz-appearance: textfield;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<form action=\"a.pr\" method=\"post\">\n");
      out.write("\n");
      out.write("   <div class=\"wrap\">\n");
      out.write("      <div class=\"img\">\n");
      out.write("         <img src=\"imgs/shopbox.png\">\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"text_div\">\n");
      out.write("         <p id=\"name\" >아나포 스마트 약통 AnaFor Smart Box IoT 알약 / 영양제 박스</p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <hr/>\n");
      out.write("      \n");
      out.write("      <div class=\"a\">\n");
      out.write("         <p>상품가격</p>\n");
      out.write("         <p>배송안내</p>\n");
      out.write("         <p>모델명</p>\n");
      out.write("         <p>제조회사</p>\n");
      out.write("         <p>원산지</p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"b\">\n");
      out.write("         <p id=\"price\">30,000원</p>\n");
      out.write("         <p>대한통운</p>\n");
      out.write("         <p>AnaFor Smart Box Model 1</p>\n");
      out.write("         <p>AnaFor</p>\n");
      out.write("         <p>대한민국</p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"c\">\n");
      out.write("         <p id=\"line\">아나포 스마트 약통 AnaFor Smart Box IoT Model 1</p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <input class=\"cnt\" type=\"number\" value=\"1\" name=\"bk_cnt\" style=\"border: 1px solid #808080;\"><p style=\"position: absolute; width: 50px; height: 25px; left: 1480px; top: 488px;\">개</p>\n");
      out.write("      \n");
      out.write("      <div class=\"total\">\n");
      out.write("         <p class=\"total_price\">총 상품 금액</p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"money\">\n");
      out.write("         <input type=\"hidden\" name=\"bk_price\" value=\"30000\"/>\n");
      out.write("           <p class=\"money_result\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("</p>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("   </div>\n");
      out.write("	   <button type=\"button\" class=\"order\" onclick=\"order()\">주문하기</button>\n");
      out.write("	   <button type=\"button\" class=\"buy_insert\" onclick=\"basket()\">장바구니담기</button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.1/jquery-ui.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function () {\n");
      out.write("   $(\".cnt\").on(\"keyup\", function() {\n");
      out.write("      var total = (30000 * $('.cnt').val());\n");
      out.write("      $(\"[name=bk_price]\").val(total);\n");
      out.write("      total = total.toString().replace(/\\B(?<!\\.\\d*)(?=(\\d{3})+(?!\\d))/g, \",\");\n");
      out.write("      $(\".money_result\").text(total + \"원\");\n");
      out.write("   });\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("function order() {\n");
      out.write("	 \n");
      out.write("	var loginInfo =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	\n");
      out.write("	if (loginInfo != \"\"){\n");
      out.write("		\n");
      out.write("		if ($('.cnt').val() == 0 || $('.cnt').val() == \"\") {\n");
      out.write("		       alert(\"수량을 입력하세요.\");\n");
      out.write("		       $('.cnt').focus();\n");
      out.write("		       return;\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("		   alert(\"주문 페이지로 이동합니다.\");\n");
      out.write("		   $(\"form\").submit();\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	} \n");
      out.write("	else{\n");
      out.write("		alert(\"로그인 후 이용하실 수 있습니다.\");\n");
      out.write("		location = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function basket() {\n");
      out.write("	 \n");
      out.write("	var loginInfo =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("	\n");
      out.write("	if (loginInfo != \"\"){\n");
      out.write("		if ($('.cnt').val() == 0 || $('.cnt').val() == \"\") {\n");
      out.write("		       alert(\"수량을 입력하세요.\");\n");
      out.write("		       $('.cnt').focus();\n");
      out.write("		       return;\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("		   alert(\"장바구니로 이동합니다.\");\n");
      out.write("		   $(\"form\").attr(\"action\", \"b.pr\");\n");
      out.write("		   $(\"form\").submit();\n");
      out.write("		   \n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	else{\n");
      out.write("		alert(\"로그인 후 이용하실 수 있습니다.\");\n");
      out.write("		location = \"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/shop/shop.jsp(235,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue("30000");
      // /WEB-INF/views/shop/shop.jsp(235,35) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,##0원");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/shop/shop.jsp(276,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("userLogin");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/shop/shop.jsp(301,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("userLogin");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
