/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-06-23 04:08:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.my_005freview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class new_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/Study_Spring/Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/anafor/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648006669317L));
    _jspx_dependants.put("jar:file:/D:/Study_Spring/Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/anafor/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#myform fieldset{\n");
      out.write("    display: inline-block;\n");
      out.write("    direction: rtl;\n");
      out.write("    border:0;\n");
      out.write("}\n");
      out.write("#myform fieldset legend{\n");
      out.write("    text-align: right;\n");
      out.write("}\n");
      out.write("#myform input[type=radio]{\n");
      out.write("    display: none;\n");
      out.write("}\n");
      out.write("#myform label{\n");
      out.write("    font-size: 2em;\n");
      out.write("    color: transparent;\n");
      out.write("    text-shadow: 0 0 0 #f0f0f0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#myform fieldset .align{\n");
      out.write("    display: inline-block;\n");
      out.write("    direction: ltr;\n");
      out.write("    border:0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".unchecked{\n");
      out.write("    font-size: 2em;\n");
      out.write("    color: transparent;\n");
      out.write("    text-shadow: 0 0 0 #f0f0f0;\n");
      out.write("}\n");
      out.write(".checked{\n");
      out.write("	font-size: 2em;\n");
      out.write("    color: #fad000;    \n");
      out.write("}\n");
      out.write("\n");
      out.write("#myform .hover:hover{\n");
      out.write("    text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);\n");
      out.write("}\n");
      out.write("#myform .hover:hover ~ label{\n");
      out.write("    text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);\n");
      out.write("}\n");
      out.write("\n");
      out.write("#myform input[type=radio]:checked ~ label {\n");
      out.write("	text-shadow: 0 0 0 rgba(250, 208, 0, 0.99);\n");
      out.write("}\n");
      out.write("\n");
      out.write("#reviewContents {\n");
      out.write("    width: 100%;\n");
      out.write("    height: 150px;\n");
      out.write("    padding: 10px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    border: solid 1.5px #D3D3D3;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    font-size: 16px;\n");
      out.write("    resize: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("		<form action=\"review_insert.rev\" name=\"myform\" id=\"myform\" method=\"post\">\n");
      out.write("				\n");
      out.write("		<div style=\"background-color:#929292; width: 100%; height: 60px; padding: 20px;\">\n");
      out.write("			<h3 style=\"font-size: 25px; font-weight: bold; text-align: left; color: white;\">리뷰 쓰기</h3>\n");
      out.write("		</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("		 <div style=\"margin: 30px; background-color: white; width: 96.5%; height: 500px; padding: 20px;\">\n");
      out.write("		\n");
      out.write("		<table style=\"width: 80%; margin-top: 100px; margin-bottom: 20px;\">\n");
      out.write("		<tr>\n");
      out.write("			<th style=\"width: 150px;\">별점</th>\n");
      out.write("			<td style=\"text-align: left;\">\n");
      out.write("				<fieldset>\n");
      out.write("						<span class=\"text-bold\">별점을 선택해주세요</span>\n");
      out.write("						<input type=\"radio\" name=\"rev_grade\" value=\"5\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rev_grade eq 5 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" id=\"rate5\"><label class='hover'  for=\"rate5\">⭐</label>\n");
      out.write("						<input type=\"radio\" name=\"rev_grade\" value=\"4\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rev_grade eq 4 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" id=\"rate4\"><label class='hover'  for=\"rate4\">⭐</label>\n");
      out.write("						<input type=\"radio\" name=\"rev_grade\" value=\"3\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rev_grade eq 3 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" id=\"rate3\"><label class='hover'  for=\"rate3\">⭐</label>\n");
      out.write("						<input type=\"radio\" name=\"rev_grade\" value=\"2\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rev_grade eq 2 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" id=\"rate2\"><label class='hover'  for=\"rate2\">⭐</label>\n");
      out.write("						<input type=\"radio\" name=\"rev_grade\" value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rev_grade eq 1 ? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" id=\"rate1\"><label class='hover'  for=\"rate1\">⭐</label>\n");
      out.write("					</fieldset>\n");
      out.write("			</td>\n");
      out.write("			<th style=\"width: 100px;\">작성자</th>\n");
      out.write("			<td style=\"width: 200px;\">\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("				<input type=\"hidden\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("			</td>\n");
      out.write("			\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>제목</th>\n");
      out.write("			<td colspan=\"5\" style=\"text-align: left;\">\n");
      out.write("				<input type=\"text\"name=\"rev_title\"  class=\"chk\"\n");
      out.write("				 style=\"height: 30px; font-size: 20px; line-height: 30px; text-align: left;\" />\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>내용</th>\n");
      out.write("			<td colspan=\"5\" style=\"text-align: left; height: 450px; \">\n");
      out.write("				<input type=\"text\"  name=\"rev_content\" class=\"chk\"\n");
      out.write("				style=\"text-align: left; height: 500px; margin-bottom: 20px; padding: 20px; font-size: 15px; width: 98.5%; margin-right: 20px; font-size: 15px;\" />\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("			");
      out.write("\n");
      out.write("			 \n");
      out.write("			<div>\n");
      out.write("				<a class=\"btn-fill\" onclick=\" if(emptyCheck() ) { $('form').submit() }\">저장하기</a>&nbsp;&nbsp;&nbsp;	\n");
      out.write("				<a class=\"btn-empty\" href=\"shopList.my\">취소하기</a>\n");
      out.write("			</div>\n");
      out.write("	\n");
      out.write("		</div>\n");
      out.write("	</form>	\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
