/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-06-17 03:20:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Study_Spring/Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/anafor/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1648006669317L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>대시보드</title>\n");
      out.write("<script type=\"text/javascript\" src=\"js/admin.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("/*style.css*/\n");
      out.write("#wrap{width: 100%; height: auto;}\n");
      out.write("#logo{width: 100%; height: 60px; position: relative; border-bottom: 1px solid #d9d9d9;}\n");
      out.write("\n");
      out.write("#logo h3{color: #fff; position: absolute; left: 80px; top: 5px; font-weight: 600; font-size: 30px; line-height: 32px;}\n");
      out.write("#logo p{display: block; color: #fff; position: absolute; left: 105px; top: 30px; font-weight: 600; font-size: 14px;line-height: 20px}\n");
      out.write("\n");
      out.write("#dormammu{width: 100%; height: auto; position: relative; }\n");
      out.write("#dormammu ul{position:absolute; width: 100%; height: 30px; left: 5px; top: 20px; }\n");
      out.write("#dormammu ul li a{font-weight: 600; font-size: 20px; line-height: 30px;}\n");
      out.write("#dormammu ul li img{margin-right: 30px;}\n");
      out.write("\n");
      out.write("#container{width: 100%; height: auto; position: relative; }\n");
      out.write("#container ul{position:absolute; width: 100%; height: auto; left: 0; top: 100px; margin-left: 15px;}\n");
      out.write("#container ul li a{font-weight: 600; font-size: 18px; line-height: 40px; text-align: center;}\n");
      out.write("#container ul li a:hover{font-weight: bold; color : #b0b0b0;}\n");
      out.write("#container ul li img{margin-right: 30px;}\n");
      out.write("\n");
      out.write("/*v1*/\n");
      out.write("#nav-v1{position:relative; width:100%;text-align: left; }\n");
      out.write(".menu-v1{	line-height:0;}\n");
      out.write("/* .menu-v1:hover{background-color:#414141;}\n");
      out.write(".menu-v1:hover>a{color:white;font-weight:bold;}\n");
      out.write(" */\n");
      out.write(".menu-v1 .submenu{background-color:#414141;	display:none; margin-left: 30px; margin-top: 30px;}\n");
      out.write("/* .menu-v1 .submenu{position:absolute; top: 80px; background-color:#414141;	display:none; margin-left: 30px; margin-top: 30px;} */\n");
      out.write("\n");
      out.write("/* .menu-v1 .submenu li:hover{	background-color:#000;color:#414141;font-weight:bold;} */\n");
      out.write("\n");
      out.write("/* #dormammu ul li a:hover, header .category ul li a.active {font-weight: bold; color : #b0b0b0;} */\n");
      out.write("#dormammu ul li a:hover, #dormammu ul li a:active {font-weight: bold; color : #b0b0b0;}\n");
      out.write("#dormammu ul{text-decoration: none;}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div id=\"wrap\">\n");
      out.write("\n");
      out.write("	<div id=\"logo\">\n");
      out.write("		<h3>AnaFor</h3>\n");
      out.write("		<p>관리자 센터</p>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div id=\"dormammu\">\n");
      out.write("		<ul>\n");
      out.write("			<li><img alt=\"돌아가기\" src=\"imgs/dormammu.png\"><a href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("' id=\"logo\">사이트 돌아가기</a></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<div id=\"container\">\n");
      out.write("			\n");
      out.write("			<ul id=\"nav-v1\">\n");
      out.write("				<li class=\"menu-v1\"><img alt=\"\" src=\"imgs/dash.png\"><a href=\"admin\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category eq 'bo' ? 'class=\"active\"' : '' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" >대시보드</a>\n");
      out.write("					\n");
      out.write("				</li>\n");
      out.write("				\n");
      out.write("				<li class=\"menu-v1\"><img alt=\"\" src=\"imgs/person.png\"><a href=\"user.ur\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category eq 'ur' ? 'class=\"active\"' : '' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">사용자관리</a>\n");
      out.write("\n");
      out.write("									\n");
      out.write("				</li>\n");
      out.write("				<li class=\"menu-v1\"><img alt=\"\" src=\"imgs/note.png\"><a href=\"list.co\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category eq 'co' ? 'class=\"active\"' : '' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">컨텐츠관리</a>\n");
      out.write("					<!-- <ul class=\"submenu\">\n");
      out.write("						<li><a href=\"#\">Q&A</a></li>\n");
      out.write("						<li><a href=\"#\">FAQ</a></li>\n");
      out.write("						<li><a href=\"#\">리뷰</a></li>\n");
      out.write("						<li><a href=\"#\">공지사항</a></li>\n");
      out.write("					</ul> -->				\n");
      out.write("				</li>\n");
      out.write("				<li class=\"menu-v1\"><img alt=\"\" src=\"imgs/cart.png\"><a href=\"shopList.sp\">Shop관리</a>\n");
      out.write("									\n");
      out.write("				</li>\n");
      out.write("				<li class=\"menu-v1\"><img alt=\"\" src=\"imgs/cart.png\"><a href=\"list.sp\">리뷰관리</a>\n");
      out.write("									\n");
      out.write("				</li>\n");
      out.write("				<li class=\"menu-v1\"><img alt=\"\" src=\"imgs/Group.png\"><a href=\"statistics.st\">통계</a>\n");
      out.write("									\n");
      out.write("				</li>\n");
      out.write("			</ul>	\n");
      out.write("	</div>\n");
      out.write("</div>			\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/include/menu.jsp(63,56) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
